apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: reader-inquisitor
    service: backend
spec:
  selector:
    matchLabels:
      app: reader-inquisitor
      service: backend
  template:
    metadata:
      labels:
        app: reader-inquisitor
        service: backend
    spec:
      containers:
      - name: backend
        image: backend
        imagePullPolicy: Never
        command: ["npm"]
        args: ["run", "start"]
        env:
        - name: PORT
          value: "3000"
        ports:
        - containerPort: 3000
      