apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
  labels:
    app: reader-inquisitor
    service: database
spec:
  selector:
    matchLabels:
      app: reader-inquisitor
      service: database
  template:
    metadata:
      labels:
        app: reader-inquisitor
        service: database
    spec:
      containers:
      - name: database
        image: flopag/reader-inquisitor_database
        imagePullPolicy: Always
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: reader-inquisitor-database
                key: MYSQL_ROOT_PASSWORD
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: database