apiVersion: apps/v1
kind: Deployment
metadata:
  name: bot
  labels:
    app: reader-inquisitor
    service: bot
spec:
  selector:
    matchLabels:
      app: reader-inquisitor
      service: bot
  template:
    metadata:
      labels:
        app: reader-inquisitor
        service: bot
    spec:
      containers:
      - name: bot
        image: flopag/reader-inquisitor_bot
        imagePullPolicy: Always
        command: ["npm"]
        args: ["run", "start"]
        readinessProbe:
          exec:
            command:
              - /bin/sh
              - -c
              - ./healthcheck.sh
          initialDelaySeconds: 10
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 6
        env:
        - name: PORT
          value: "3002"
        - name: BACKEND_URL
          value: "<to_replace>"
        - name: POWER_USER_PASS
          valueFrom:
            secretKeyRef:
              name: express
              key: POWER_USER_PASS
        ports:
        - containerPort: 3002
      