apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
  labels:
    app: reader-inquisitor
    service: database
spec:
  selector:
    matchLabels:
      app: reader-inquisitor
      service: database
  template:
    metadata:
      labels:
        app: reader-inquisitor
        service: database
    spec:
      containers:
      - name: database
        image: flopag/reader-inquisitor_database
        imagePullPolicy: Always
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql
        readinessProbe:
          exec:
            command:
              - /bin/sh
              - -c
              - ./healthcheck.sh
          initialDelaySeconds: 10
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 6
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: database
                key: MYSQL_PASSWORD
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: database