apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: reader-inquisitor
    service: frontend
spec:
  selector:
    matchLabels:
      app: reader-inquisitor
      service: frontend
  template:
    metadata:
      labels:
        app: reader-inquisitor
        service: frontend
    spec:
      containers:
      - name: frontend
        image: flopag/reader-inquisitor_frontend
        imagePullPolicy: Always
        command: ["npm"]
        args: ["run", "start"]
        ports:
        - containerPort: 1234
        readinessProbe:
          exec:
            command:
              - /bin/sh
              - -c
              - ./healthcheck.sh
          initialDelaySeconds: 10
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 6