apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: NodePort
  selector:
    app: reader-inquisitor
    service: frontend
  ports:
    - protocol: TCP
      port: 1234
      targetPort: 1234
      nodePort: 30000