apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  template:
    spec:
      containers:
      - name: backend
        env:
        - name: MYSQL_HOST
          value: "e2e-database"
        - name: DISCORD_CALLBACK_URL
          value: "todetermine"
        - name: IS_TESTING
          value: "justarandomstring"
