apiVersion: apps/v1
kind: Deployment
metadata:
  name: bot
spec:
  template:
    spec:
      containers:
      - name: bot
        env:
        - name: BACKEND_URL
          value: "http://e2e-backend-backdoor:4000"
