name: backend-deployment
on: 
  workflow_call:
    inputs:
      build_tag:
        required: true
        type: string
    secrets:
      SSH_SERVER_HOST:
        required: true
      SSH_SERVER_PASSWORD:
        required: true
      SSH_SERVER_USERNAME:
        required: true
jobs:
  deployment:
    runs-on: 
      ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: deploy image via ssh
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_SERVER_HOST }}
          username: ${{ secrets.SSH_SERVER_USERNAME }}
          password: ${{ secrets.SSH_SERVER_PASSWORD }}
          script: kubectl set image deployment/backend backend=${{ secrets.DOCKER_HUB_USERNAME }}/reader-inquisitor_backend:${{ inputs.build_tag }}
      - name: Verify the rollout using ssh
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_SERVER_HOST }}
          username: ${{ secrets.SSH_SERVER_USERNAME }}
          password: ${{ secrets.SSH_SERVER_PASSWORD }}
          script: |
            if ! kubectl rollout status deployment/backend --timeout=180s; then
              kubectl rollout undo deployment/backend
              exit 1
            fi
