name: config_update_prod
on: 
  workflow_call:
jobs:
  deployment:
    runs-on: 
      ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Copy files via SSH
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          source: "infra/kubernetes"
          target: ~/app
      - name: deploy image via ssh
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_SERVER_HOST }}
          username: ${{ secrets.SSH_SERVER_USERNAME }}
          password: ${{ secrets.SSH_SERVER_PASSWORD }}
          script: kubectl apply -k ~/app/kubernetes/overlays/prod
