name: frontend-deployment
on: 
  workflow_call:
jobs:
  deployment:
    runs-on: 
      ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: deploy image via ssh
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_SERVER_HOST }}
          username: ${{ secrets.SSH_SERVER_USERNAME }}
          password: ${{ secrets.SSH_SERVER_PASSWORD }}
          script: kubectl set image deployment/frontend frontend=${{ secrets.DOCKER_HUB_USERNAME }}/reader-inquisitor_frontend:${{ github.sha }}
      - name: Verify the rollout using ssh
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_SERVER_HOST }}
          username: ${{ secrets.SSH_SERVER_USERNAME }}
          password: ${{ secrets.SSH_SERVER_PASSWORD }}
          script: |
            if ! kubectl rollout status deployment/frontend --timeout=180s; then
              kubectl rollout undo deployment/frontend
              exit 1
            fi
